### ISSUE TITLE
[feature] add writing support

### ISSUE THREAD

**Issue by lizelive** [UgnilJoZ/rust-minetestworld#2]
it would be very cool to be able to generate worlds using rust

**Comment by UgnilJoZ** [comment]
I agree, this would be very nice indeed. I intend to implement some kind of "Voxel Manipulator" type, which edits and caches mapblocks.

**Comment by UgnilJoZ** [comment]
#3 does a large part of this. The new [`VoxelManip`](https://docs.rs/minetestworld/0.5.0-rc.1/minetestworld/voxel_manip/struct.VoxelManip.html) struct allows for more convenient interaction with a map at voxel-level, and also supports writing.

See also [the example](https://github.com/UgnilJoZ/rust-minetestworld/blob/main/examples/modify_map.rs)!

**Comment by UgnilJoZ** [comment]
I finally released version 0.5, which has is the possibility to [create](https://docs.rs/minetestworld/latest/minetestworld/world/struct.World.html#method.create_sqlite) a map (sqlite only for now, so if you want another backend, you have to [migrate](https://wiki.minetest.net/Database_backends)) and [modify](https://docs.rs/minetestworld/latest/minetestworld/world/struct.World.html#method.get_voxel_manip) it. [Here is a full example](https://github.com/UgnilJoZ/rust-minetestworld/blob/main/examples/create_world.rs).
